import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Vegetables', image: 'https://i.ibb.co/Z6xywGnX/vagitable.jpg', icon: 'LeafyGreen' },
  { id: '2', name: 'Fruits', image: 'https://i.ibb.co/LD7HG3Rf/fruits-getty.webp', icon: 'Apple' },
  { id: '3', name: 'Daily Essentials', image: 'https://i.ibb.co/Pvb66GZp/daily-essetial.avif', icon: 'Container' },
  { id: '4', name: 'Snacks', image: 'https://i.ibb.co/CS60RhY/snaks.jpg', icon: 'Cookie' },
  { id: '5', name: 'Beverages', image: 'https://i.ibb.co/7NKmb0dQ/bevrach.jpg', icon: 'GlassWater' },
  { id: '6', name: 'Bakery', image: 'https://i.ibb.co/YFYrZXpB/bakers.jpg', icon: 'Croissant' },
];

export const PRODUCTS: Product[] = [
  {
    id: 't1',
    name: 'Tata Salt',
    category: 'Grocery Essentials',
    price: 30,
    originalPrice: 35,
    rating: 4.8,
    badge: 'Best Seller',
    isTrending: true,
    image: 'https://i.ibb.co/QL79ysy/image.png',
    images: ['https://i.ibb.co/QL79ysy/image.png'],
    description: 'Tata Salt, Vacuum Evaporated Iodised Salt.',
    reviewsCount: 156,
    unit: '1 kg'
  },
  {
    id: 't2',
    name: 'Dettol Original Soap Reliable Protect Pine Scent - 70 gm',
    category: 'Personal Care',
    price: 49,
    originalPrice: 60,
    rating: 4.7,
    badge: 'Popular',
    isTrending: true,
    image: 'https://i.ibb.co/7mcFJw3/image.png',
    images: ['https://i.ibb.co/7mcFJw3/image.png'],
    description: 'Dettol Original Soap Reliable Protect Pine Scent - 70 gm',
    reviewsCount: 89,
    unit: '70 gm'
  },
  {
    id: 't3',
    name: 'Saffola Rolled Oats, Delicious Creamy Oats, High Protein & Fibre',
    category: 'Breakfast & Health Foods',
    price: 179,
    originalPrice: 220,
    rating: 4.7,
    badge: 'Healthy Choice',
    isTrending: true,
    image: 'https://i.ibb.co/HfcLSM4H/image.png',
    images: ['https://i.ibb.co/HfcLSM4H/image.png'],
    description: 'Saffola Rolled Oats, Delicious Creamy Oats, High Protein & Fibre.',
    reviewsCount: 231,
    unit: '1 kg'
  },
  {
    id: 't4',
    name: 'Nourishing Body Wash, Nourishing Care, 20 fl oz (591 ml)',
    category: 'Personal Care',
    price: 299,
    originalPrice: 349,
    rating: 4.6,
    badge: 'Trending',
    isTrending: true,
    image: 'https://i.ibb.co/cSQQtmbx/image.png',
    images: ['https://i.ibb.co/cSQQtmbx/image.png'],
    description: 'Nourishing Body Wash, Nourishing Care, 20 fl oz (591 ml)',
    reviewsCount: 178,
    unit: '591 ml'
  },
  {
    id: 't5',
    name: 'Head & Shoulders Anti-Dandruff Shampoo',
    category: 'Personal Care',
    price: 299,
    originalPrice: 349,
    rating: 4.7,
    badge: 'Best Seller',
    isTrending: true,
    image: 'https://i.ibb.co/gb2vf591/image.png',
    images: ['https://i.ibb.co/gb2vf591/image.png'],
    description: 'Head & Shoulders Anti-Dandruff Shampoo',
    reviewsCount: 156,
    unit: '1 bottle'
  },
  {
    id: 't6',
    name: 'Crunchy Granola Roasted Nuts, Low Sugar 400g | Bamboo',
    category: 'Healthy Breakfast',
    price: 249,
    originalPrice: 299,
    rating: 4.8,
    badge: 'Healthy Choice',
    isTrending: true,
    image: 'https://i.ibb.co/HLCR7vDC/image.png',
    images: ['https://i.ibb.co/HLCR7vDC/image.png'],
    description: 'Crunchy Granola Roasted Nuts, Low Sugar 400g by Bamboo',
    reviewsCount: 89,
    unit: '400g'
  },
  {
    id: 's1',
    name: 'Kurkure Masala Munch Crisps',
    category: 'Snacks',
    price: 20,
    originalPrice: 25,
    rating: 4.8,
    badge: 'Summer Favorite',
    isSummerSpecial: true,
    image: 'https://i.ibb.co/C5Xb866V/image.png',
    images: ['https://i.ibb.co/C5Xb866V/image.png'],
    description: 'Kurkure Masala Munch Crisps',
    reviewsCount: 120,
    unit: '1 pack'
  },
  {
    id: 's2',
    name: 'Classic Potato Chips',
    category: 'Snacks',
    price: 30,
    originalPrice: 40,
    rating: 4.6,
    badge: 'Best Seller',
    isSummerSpecial: true,
    image: 'https://i.ibb.co/9CLjCdD/image.png',
    images: ['https://i.ibb.co/9CLjCdD/image.png'],
    description: 'Classic Potato Chips',
    reviewsCount: 85,
    unit: '1 pack'
  },
  {
    id: 's3',
    name: 'Kala Chana',
    category: 'Healthy Snacks',
    price: 80,
    originalPrice: 95,
    rating: 4.7,
    badge: 'Healthy Choice',
    isSummerSpecial: true,
    image: 'https://i.ibb.co/jvMzYt4z/image.png',
    images: ['https://i.ibb.co/jvMzYt4z/image.png'],
    description: 'Kala Chana',
    reviewsCount: 64,
    unit: '500 g'
  },
  {
    id: 's4',
    name: 'Amul Milk',
    category: 'Dairy Products',
    price: 35,
    originalPrice: 40,
    rating: 4.9,
    badge: 'Fresh Daily',
    isSummerSpecial: true,
    image: 'https://i.ibb.co/F4g9kRJp/image.png',
    images: ['https://i.ibb.co/F4g9kRJp/image.png'],
    description: 'Amul Milk',
    reviewsCount: 412,
    unit: '500 ml'
  },
  {
    id: 'v1',
    name: 'Fresh Tomato',
    category: 'Vegetables',
    price: 40,
    originalPrice: 50,
    rating: 4.8,
    badge: 'Fresh',
    image: 'https://i.ibb.co/V0QdnQxs/image.png',
    images: ['https://i.ibb.co/V0QdnQxs/image.png'],
    description: 'Fresh Tomato',
    reviewsCount: 156,
    unit: '1 kg'
  },
  {
    id: 'v2',
    name: 'Fresh Broccoli',
    category: 'Vegetables',
    price: 90,
    originalPrice: 110,
    rating: 4.9,
    badge: 'Organic',
    image: 'https://i.ibb.co/JwgBKZv4/image.png',
    images: ['https://i.ibb.co/JwgBKZv4/image.png'],
    description: 'Fresh Broccoli',
    reviewsCount: 94,
    unit: '1 kg'
  },
  {
    id: 'p1',
    name: 'Organic Vine Tomatoes',
    category: 'Vegetables',
    price: 49,
    originalPrice: 60,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=800&fm=webp',
    images: [
      'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&q=80&w=1200&fm=webp',
      'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=1200&fm=webp'
    ],
    description: 'Farm-fresh organic tomatoes, picked at peak ripeness. Perfect for salads, sauces, and sandwiches. Rich in Vitamin C and antioxidants.',
    rating: 4.8,
    reviewsCount: 124,
    unit: '1 kg',
  },
  {
    id: 'p2',
    name: 'Premium Alphanso Mangoes',
    category: 'Fruits',
    price: 599,
    originalPrice: 750,
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=800&fm=webp',
    images: [
      'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=1200&fm=webp',
      'https://images.unsplash.com/photo-1591073113125-e46713c829ed?auto=format&fit=crop&q=80&w=1200&fm=webp'
    ],
    description: 'The king of fruits! Sweet, juicy, and legendary Alphanso mangoes from the finest orchards. Naturally ripened.',
    rating: 4.9,
    reviewsCount: 89,
    unit: '1 dozen',
  },
  {
    id: 'p3',
    name: 'Organic Fresh Broccoli',
    category: 'Vegetables',
    price: 89,
    originalPrice: 110,
    image: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&q=80&w=800&fm=webp',
    images: [
      'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&q=80&w=1200&fm=webp'
    ],
    description: 'Fresh green organic broccoli. High in fiber and protein, perfect for steaming or stir-frying.',
    rating: 4.7,
    reviewsCount: 56,
    isOffer: true,
    unit: '500 g',
  },
  {
    id: 'p4',
    name: 'Crunchy Chocolate Granola',
    category: 'Snacks',
    price: 249,
    image: 'https://images.unsplash.com/photo-1517093297699-14375bc162e7?auto=format&fit=crop&q=80&w=800&fm=webp',
    images: [
      'https://images.unsplash.com/photo-1517093297699-14375bc162e7?auto=format&fit=crop&q=80&w=1200&fm=webp'
    ],
    description: 'Oats, nuts, and chocolate chips roasted to perfection for a healthy and tasty breakfast snack.',
    rating: 4.5,
    reviewsCount: 230,
    unit: '400 g',
  },
  {
    id: 'p5',
    name: 'Pure Himalayan Honey',
    category: 'Daily Essentials',
    price: 349,
    originalPrice: 400,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=800&fm=webp',
    images: [
      'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=1200&fm=webp'
    ],
    description: '100% pure and natural honey sourced from the high-altitude Himalayan ranges. No added sugar.',
    rating: 4.8,
    reviewsCount: 112,
    unit: '500 g',
  },
  {
    id: 'p6',
    name: 'Freshly Baked Baguette',
    category: 'Bakery',
    price: 75,
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddf13cf?auto=format&fit=crop&q=80&w=800&fm=webp',
    images: [
      'https://images.unsplash.com/photo-1586444248902-2f64eddf13cf?auto=format&fit=crop&q=80&w=1200&fm=webp'
    ],
    description: 'Crusty on the outside, soft on the inside. Baked fresh daily with premium flour.',
    rating: 4.6,
    reviewsCount: 78,
    unit: '1 pc',
  },
  {
    id: 'p7',
    name: 'Premium Hass Avocado (Pair)',
    category: 'Fruits',
    price: 399,
    originalPrice: 500,
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&q=80&w=800&fm=webp',
    images: [
      'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&q=80&w=1200&fm=webp'
    ],
    description: 'Creamy Hass avocados, imported and perfectly ripe. Great for guacamole or toast.',
    rating: 4.8,
    reviewsCount: 45,
    unit: '2 pcs',
  },
  {
    id: 'p8',
    name: 'Sparkling Apple Juice',
    category: 'Beverages',
    price: 120,
    image: 'https://images.unsplash.com/photo-1600271886332-699bb27c91fc?auto=format&fit=crop&q=80&w=800&fm=webp',
    images: [
      'https://images.unsplash.com/photo-1600271886332-699bb27c91fc?auto=format&fit=crop&q=80&w=1200&fm=webp'
    ],
    description: 'Refreshing sparkling juice made from 100% natural apples. No preservatives.',
    rating: 4.4,
    reviewsCount: 67,
    unit: '330 ml',
  },
];
